export const products = [
  {
    id: '1',
    slug: 'website-development',
    name: 'Website Development',
    price: 1200,
    compareAt: 1800,
    category: 'Development',
    badge: 'Most Popular',
    rating: 5.0,
    reviews: 87,
    image: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1547658719-da2b51169166?w=600&q=80',
      'https://images.unsplash.com/photo-1593720213428-28a5b9e94613?w=600&q=80',
    ],
    description: 'Custom websites built with the latest technologies — fast, responsive, and optimised for conversions. From landing pages to complex web applications, we craft digital experiences that impress and perform.',
    benefits: ['Responsive on all devices', 'SEO-ready structure', 'Fast page load speeds', 'Custom design tailored to your brand'],
    howToUse: 'Discovery call → Design mockups → Development → Testing → Launch. We work closely with you at every step and deliver within the agreed timeline with full documentation and handover.',
    ingredients: 'Next.js, React, Tailwind CSS, Node.js, PostgreSQL, Vercel, AWS',
    inStock: true,
  },
  {
    id: '2',
    slug: 'seo-optimisation',
    name: 'SEO Optimisation',
    price: 600,
    compareAt: null,
    category: 'Marketing',
    badge: 'High ROI',
    rating: 4.9,
    reviews: 63,
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80',
    ],
    description: 'Data-driven SEO strategy that gets your website to the top of Google. Comprehensive technical audits, content optimisation, link building, and transparent monthly reporting included.',
    benefits: ['Full technical SEO audit', 'Keyword research & strategy', 'On-page & off-page optimisation', 'Monthly performance reports'],
    howToUse: 'We audit your current site, identify gaps and opportunities, then implement a tailored SEO roadmap — with transparent reporting and measurable results delivered every month.',
    ingredients: 'Google Search Console, Ahrefs, Screaming Frog, Semrush, Google Analytics 4',
    inStock: true,
  },
  {
    id: '3',
    slug: 'ui-ux-design',
    name: 'UI/UX Design',
    price: 900,
    compareAt: 1200,
    category: 'Design',
    badge: 'Award-Winning',
    rating: 5.0,
    reviews: 45,
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&q=80',
    ],
    description: 'Beautiful, intuitive interfaces that delight users and drive results. From wireframes to pixel-perfect designs — we turn your vision into a compelling digital experience your customers will love.',
    benefits: ['User research & personas', 'Wireframes & interactive prototypes', 'Pixel-perfect Figma files', 'Design system & component library'],
    howToUse: 'Discovery → User research → Wireframing → Visual design → Prototype → Developer handoff. We collaborate closely at every stage to ensure the design truly reflects your brand and goals.',
    ingredients: 'Figma, Adobe Illustrator, Framer, Lottie, Principle, Zeplin',
    inStock: true,
  },
  {
    id: '4',
    slug: 'business-solutions',
    name: 'Business Solutions',
    price: 2500,
    compareAt: null,
    category: 'Enterprise',
    badge: null,
    rating: 4.8,
    reviews: 29,
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&q=80',
    ],
    description: 'End-to-end digital transformation for your business. Custom CRMs, ERPs, workflow automation, and third-party integrations — built to scale with your team and evolve with your needs.',
    benefits: ['Custom CRM / ERP systems', 'Process & workflow automation', 'Third-party API integrations', 'Ongoing support & maintenance'],
    howToUse: 'We analyse your current workflows, map out the ideal digital architecture, and build a bespoke solution — then train your team and provide ongoing support and iteration.',
    ingredients: 'Node.js, Python, PostgreSQL, REST & GraphQL APIs, Zapier, Make, Supabase, AWS',
    inStock: true,
  },
  {
    id: '5',
    slug: 'ecommerce-development',
    name: 'E-commerce Development',
    price: 1800,
    compareAt: 2400,
    category: 'E-commerce',
    badge: 'Best Value',
    rating: 4.9,
    reviews: 54,
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=80',
    ],
    description: 'High-converting online stores built for growth. From product pages to checkout flows, we craft e-commerce experiences that turn visitors into loyal, returning customers.',
    benefits: ['Custom storefront design', 'Payment gateway integration', 'Inventory & order management', 'Mobile-first & SEO optimised'],
    howToUse: 'We plan your store structure, design the UI, integrate payments and shipping, and launch — then monitor performance and iterate to maximise your conversion rate.',
    ingredients: 'Next.js, Shopify, WooCommerce, Stripe, PayPal, Supabase, Vercel',
    inStock: true,
  },
]

export function getProductBySlug(slug) {
  return products.find(p => p.slug === slug) || null
}

export function getFeaturedProducts() {
  return products.slice(0, 4)
}
