export const products = [
  {
    id: '1',
    slug: 'radiance-vitamin-c-serum',
    name: 'Radiance Vitamin C Serum',
    price: 42.00,
    compareAt: 58.00,
    category: 'Skincare',
    badge: 'Best Seller',
    rating: 4.8,
    reviews: 312,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80',
      'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=600&q=80',
    ],
    description: 'A potent 15% Vitamin C serum that visibly brightens skin, fades dark spots, and boosts collagen production. Formulated with stabilised L-ascorbic acid, hyaluronic acid, and vitamin E for maximum efficacy.',
    benefits: ['Brightens & evens skin tone', 'Reduces fine lines', 'Boosts collagen', 'Antioxidant protection'],
    howToUse: 'Apply 3–4 drops to clean, dry skin every morning. Follow with moisturiser and SPF.',
    ingredients: 'Aqua, Ascorbic Acid (15%), Glycerin, Niacinamide, Sodium Hyaluronate, Tocopherol, Ferulic Acid',
    inStock: true,
  },
  {
    id: '2',
    slug: 'hydra-boost-moisturiser',
    name: 'HydraBoost Daily Moisturiser',
    price: 36.00,
    compareAt: null,
    category: 'Skincare',
    badge: 'New',
    rating: 4.7,
    reviews: 187,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80',
    ],
    description: '72-hour hydration moisturiser with hyaluronic acid complex and ceramides. Suitable for all skin types, fragrance-free, and dermatologist tested.',
    benefits: ['72-hour hydration', 'Strengthens skin barrier', 'Fragrance-free', 'Non-comedogenic'],
    howToUse: 'Apply morning and evening to face and neck after serum.',
    ingredients: 'Aqua, Glycerin, Sodium Hyaluronate, Ceramide NP, Ceramide AP, Niacinamide, Panthenol',
    inStock: true,
  },
  {
    id: '3',
    slug: 'rose-glow-face-oil',
    name: 'Rose Glow Face Oil',
    price: 54.00,
    compareAt: 68.00,
    category: 'Skincare',
    badge: null,
    rating: 4.9,
    reviews: 94,
    image: 'https://images.unsplash.com/photo-1617897903246-719242758050?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1617897903246-719242758050?w=600&q=80',
    ],
    description: 'Luxurious facial oil with rosehip, squalane, and sea buckthorn. Rich in omega fatty acids and antioxidants for a natural, healthy glow.',
    benefits: ['Deep nourishment', 'Anti-ageing', 'Natural radiance', 'Absorbs quickly'],
    howToUse: 'Warm 2–3 drops between palms and press gently onto skin. Use morning or evening.',
    ingredients: 'Rosa Canina Fruit Oil, Squalane, Hippophae Rhamnoides Oil, Tocopherol, Rosmarinus Officinalis',
    inStock: true,
  },
  {
    id: '4',
    slug: 'clarifying-salicylic-cleanser',
    name: 'Clarifying Salicylic Cleanser',
    price: 28.00,
    compareAt: null,
    category: 'Skincare',
    badge: null,
    rating: 4.6,
    reviews: 241,
    image: 'https://images.unsplash.com/photo-1601612628452-9e99ced43524?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1601612628452-9e99ced43524?w=600&q=80',
    ],
    description: 'Gentle daily cleanser with 2% salicylic acid to unclog pores, control oil, and prevent breakouts without stripping the skin.',
    benefits: ['Unclogs pores', 'Controls oil', 'Prevents breakouts', 'Gentle daily use'],
    howToUse: 'Massage onto wet skin for 60 seconds, rinse thoroughly. Use morning and evening.',
    ingredients: 'Aqua, Salicylic Acid (2%), Cocamidopropyl Betaine, Aloe Barbadensis Leaf Juice, Panthenol',
    inStock: true,
  },
  {
    id: '5',
    slug: 'retinol-renewal-night-cream',
    name: 'Retinol Renewal Night Cream',
    price: 62.00,
    compareAt: 79.00,
    category: 'Skincare',
    badge: 'Popular',
    rating: 4.8,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80',
    ],
    description: '0.3% encapsulated retinol night cream with peptides and bakuchiol. Visibly reduces wrinkles and improves skin texture with minimal irritation.',
    benefits: ['Reduces wrinkles', 'Improves texture', 'Minimises pores', 'Encapsulated for gentleness'],
    howToUse: 'Apply a pea-sized amount to face and neck every evening. Avoid eye area. Use SPF the following morning.',
    ingredients: 'Aqua, Retinol (0.3% encapsulated), Bakuchiol, Peptide Complex, Shea Butter, Squalane',
    inStock: true,
  },
]

export function getProductBySlug(slug) {
  return products.find(p => p.slug === slug) || null
}

export function getFeaturedProducts() {
  return products.slice(0, 4)
}
